{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "6139abea",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2023-08-27 13:16:18,756\tINFO worker.py:1621 -- Started a local Ray instance.\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m 'Adam' object has no attribute 'build'\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 387, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 268, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     model = deserialize_keras_object(\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     instance.compile_from_config(compile_config)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     self.optimizer.build(self.trainable_variables)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m     return super().__getattribute__(name)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9147)\u001b[0m AttributeError: 'Adam' object has no attribute 'build'\n"
     ]
    },
    {
     "ename": "RayTaskError",
     "evalue": "\u001b[36mray::head_to_head_game()\u001b[39m (pid=9134, ip=127.0.1.1)\n  At least one of the input arguments for this task could not be computed:\nray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\ntraceback: Traceback (most recent call last):\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n    raise e\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n    model = saving_lib.load_model(filepath, safe_mode=False)\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n    raise e\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n    model = deserialize_keras_object(\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n    instance.compile_from_config(compile_config)\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n    self.optimizer.build(self.trainable_variables)\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n    raise e\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n    return super().__getattribute__(name)\nAttributeError: 'Adam' object has no attribute 'build'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRayTaskError\u001b[0m                              Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 19\u001b[0m\n\u001b[1;32m     15\u001b[0m ray\u001b[39m.\u001b[39minit()\n\u001b[1;32m     17\u001b[0m model \u001b[39m=\u001b[39m tf\u001b[39m.\u001b[39mkeras\u001b[39m.\u001b[39mmodels\u001b[39m.\u001b[39mload_model(\u001b[39m'\u001b[39m\u001b[39mNetworks/Best_Model/\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m---> 19\u001b[0m \u001b[39mprint\u001b[39m(head_to_head_match(MCTS(model), MCTS()))\n",
      "File \u001b[0;32m~/Documents/Code/IMGT657-Project/head_to_head_match.py:47\u001b[0m, in \u001b[0;36mhead_to_head_match\u001b[0;34m(mcts_1, mcts_2, num_of_games, stochastic)\u001b[0m\n\u001b[1;32m     44\u001b[0m ray\u001b[39m.\u001b[39mput(mcts_2)\n\u001b[1;32m     46\u001b[0m results \u001b[39m=\u001b[39m [head_to_head_game\u001b[39m.\u001b[39mremote(mcts_1, mcts_2) \u001b[39mfor\u001b[39;00m _ \u001b[39min\u001b[39;00m \u001b[39mrange\u001b[39m(num_of_games)]\n\u001b[0;32m---> 47\u001b[0m results \u001b[39m=\u001b[39m ray\u001b[39m.\u001b[39;49mget(results)\n\u001b[1;32m     49\u001b[0m \u001b[39mfor\u001b[39;00m i, result \u001b[39min\u001b[39;00m \u001b[39menumerate\u001b[39m(results):\n\u001b[1;32m     50\u001b[0m     \u001b[39m# Flip results as we flip players\u001b[39;00m\n\u001b[1;32m     51\u001b[0m     \u001b[39mif\u001b[39;00m i \u001b[39m%\u001b[39m \u001b[39m2\u001b[39m \u001b[39m==\u001b[39m \u001b[39m1\u001b[39m:\n",
      "File \u001b[0;32m~/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/auto_init_hook.py:24\u001b[0m, in \u001b[0;36mwrap_auto_init.<locals>.auto_init_wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     21\u001b[0m \u001b[39m@wraps\u001b[39m(fn)\n\u001b[1;32m     22\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mauto_init_wrapper\u001b[39m(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs):\n\u001b[1;32m     23\u001b[0m     auto_init_ray()\n\u001b[0;32m---> 24\u001b[0m     \u001b[39mreturn\u001b[39;00m fn(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/client_mode_hook.py:103\u001b[0m, in \u001b[0;36mclient_mode_hook.<locals>.wrapper\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    101\u001b[0m     \u001b[39mif\u001b[39;00m func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m \u001b[39m!=\u001b[39m \u001b[39m\"\u001b[39m\u001b[39minit\u001b[39m\u001b[39m\"\u001b[39m \u001b[39mor\u001b[39;00m is_client_mode_enabled_by_default:\n\u001b[1;32m    102\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mgetattr\u001b[39m(ray, func\u001b[39m.\u001b[39m\u001b[39m__name__\u001b[39m)(\u001b[39m*\u001b[39margs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[0;32m--> 103\u001b[0m \u001b[39mreturn\u001b[39;00m func(\u001b[39m*\u001b[39;49margs, \u001b[39m*\u001b[39;49m\u001b[39m*\u001b[39;49mkwargs)\n",
      "File \u001b[0;32m~/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/worker.py:2520\u001b[0m, in \u001b[0;36mget\u001b[0;34m(object_refs, timeout)\u001b[0m\n\u001b[1;32m   2518\u001b[0m     worker\u001b[39m.\u001b[39mcore_worker\u001b[39m.\u001b[39mdump_object_store_memory_usage()\n\u001b[1;32m   2519\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39misinstance\u001b[39m(value, RayTaskError):\n\u001b[0;32m-> 2520\u001b[0m     \u001b[39mraise\u001b[39;00m value\u001b[39m.\u001b[39mas_instanceof_cause()\n\u001b[1;32m   2521\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[1;32m   2522\u001b[0m     \u001b[39mraise\u001b[39;00m value\n",
      "\u001b[0;31mRayTaskError\u001b[0m: \u001b[36mray::head_to_head_game()\u001b[39m (pid=9134, ip=127.0.1.1)\n  At least one of the input arguments for this task could not be computed:\nray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\ntraceback: Traceback (most recent call last):\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n    raise e\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n    model = saving_lib.load_model(filepath, safe_mode=False)\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n    raise e\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n    model = deserialize_keras_object(\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n    instance.compile_from_config(compile_config)\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n    self.optimizer.build(self.trainable_variables)\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n    raise e\n  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n    return super().__getattribute__(name)\nAttributeError: 'Adam' object has no attribute 'build'"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m 'Adam' object has no attribute 'build'\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 387, in deserialize_objects\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     obj = self._deserialize_object(data, metadata, object_ref)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 268, in _deserialize_object\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 223, in _deserialize_msgpack_data\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/ray/_private/serialization.py\", line 213, in _deserialize_pickle5_data\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     obj = pickle.loads(in_band)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     model = deserialize_keras_object(\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     instance.compile_from_config(compile_config)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     self.optimizer.build(self.trainable_variables)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     raise e\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m   File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m     return super().__getattribute__(name)\n",
      "\u001b[2m\u001b[36m(head_to_head_game pid=9149)\u001b[0m AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:26,480\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9157, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:26,482\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9147, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:26,483\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9146, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:26,484\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9131, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:26,486\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9158, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:26,487\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9156, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,481\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9152, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,484\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9151, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,486\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9159, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,487\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9140, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,489\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9149, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,490\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9133, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,492\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9141, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,493\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9138, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n",
      "2023-08-27 13:16:27,494\tERROR worker.py:405 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): \u001b[36mray::head_to_head_game()\u001b[39m (pid=9128, ip=127.0.1.1)\n",
      "  At least one of the input arguments for this task could not be computed:\n",
      "ray.exceptions.RaySystemError: System error: 'Adam' object has no attribute 'build'\n",
      "traceback: Traceback (most recent call last):\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 48, in deserialize_model_from_bytecode\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/pickle_utils.py\", line 46, in deserialize_model_from_bytecode\n",
      "    model = saving_lib.load_model(filepath, safe_mode=False)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 277, in load_model\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/saving_lib.py\", line 242, in load_model\n",
      "    model = deserialize_keras_object(\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/saving/serialization_lib.py\", line 508, in deserialize_keras_object\n",
      "    instance.compile_from_config(compile_config)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/engine/training.py\", line 3392, in compile_from_config\n",
      "    self.optimizer.build(self.trainable_variables)\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 984, in __getattribute__\n",
      "    raise e\n",
      "  File \"/home/drew/miniconda3/envs/imgt/lib/python3.9/site-packages/keras/optimizers/legacy/optimizer_v2.py\", line 974, in __getattribute__\n",
      "    return super().__getattribute__(name)\n",
      "AttributeError: 'Adam' object has no attribute 'build'\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'\n",
    "\n",
    "import tensorflow as tf\n",
    "from TrainingManager_new import TrainingManager\n",
    "\n",
    "tf.compat.v1.disable_eager_execution()\n",
    "\n",
    "manager = TrainingManager()\n",
    "manager.train()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "imgt",
   "language": "python",
   "name": "imgt"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.17"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
